### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ruudvanderham** [dhutchison/PythonistaScripts#10]
It would be nice to provide an option (answer) to use the answer given to all subsequent question. E.g. if DropboxSync ask whether to delete or keep the file in the Dropbox directory, the user has now two possible responses. If the user adds an R (for repeat) in front of the normal resonse, this could be in following similar questions without asking the user. Particularly if whole subdirectories are moved or deleted, this is much more convenient.

I hope this is clear to you. If not, please let me know.

**Comment by dhutchison** [comment]
Sounds useful... I'll have a think about how to implement it.

**Comment by dhutchison** [comment]
I'm currently testing this. Went with appending an 'a' (for All) to the options.

**Comment by dhutchison** [comment]
Latest commit adds this feature.
