### ISSUE TITLE
Error in write_configuration()

### ISSUE THREAD

**Issue by ruudvanderham** [dhutchison/PythonistaScripts#13]
After going through the process of entering the appkey and appsecret and allowing acccess, I get a TypeError: set (['dropbox_sync/file.cache.txt']) is not JSON serialiable in write_configuration (at line 40).

**Comment by dhutchison** [comment]
@upwart  I've not got the code handy just now, is there some debug logging you can look at to see if there is anything odd in the dict before it attempts the JSON dump?

**Comment by BalurPoco** [comment]
I get the same TypeError as @upwart. I don't find anything odd in the dict.

**Comment by ruudvanderham** [comment]
@dhutchison 
I have done a little bit of debugging and found that you are trying to dump a set to json, which is apparently not possible, unless you specify a custom encoder (I hope this is correct terminology).
When I just outcomment the three statements where you make sets (don't know whether that's allowed at all), the script seems to work.
But then I get an error that re.match is not ok. When I then include an import re statement, it seems to work.

I suspect that you have a starttup script where you import re  and implement some kind of json encoding. That would explain why you don't see the errors I encountered.

**Comment by dhutchison** [comment]
Sorry, I have no idea why this worked last night. 

The whole reason I'd prioritised the config file change was so I wasn't having to copy only bits of a script to commit.

Should be resolved now.

**Comment by dhutchison** [comment]
@upwart @Balur86 can one of you test to confirm this version works for more than me?

**Comment by ruudvanderham** [comment]
@dhutchison 
Yes. It works now. Bravo.

**Comment by BalurPoco** [comment]
@dhutchison Yes, It works, but the [emtpy folders](https://github.com/dhutchison/PythonistaScripts/issues/7#issuecomment-177087454).
