### ISSUE TITLE
Disable automatic screen turn off

### ISSUE THREAD

**Issue by BalurPoco** [dhutchison/PythonistaScripts#14]
Add `console.set_idle_timer_disabled(...)` to disable automatic screen off.
You maybe add a config line for that, if someone don't want to disable.

**Comment by dhutchison** [comment]
I didn't even know that was possible. 

I'll add it in later.

**Comment by dhutchison** [comment]
@Balur86 I've added it as the default behaviour just now. If someone particularly wants it optional they can raise another issue / pull req.

**Comment by BalurPoco** [comment]
Thanks. But I think you should put a `console.set_idle_timer_disabled(False)` at the end of script, or it stay on forever while pythonista is in front?

**Comment by dhutchison** [comment]
@Balur86 I'll check again, but I didn't think that was the case.
