### ISSUE TITLE
Name not defined problem

### ISSUE THREAD

**Issue by revkamcclain** [dhutchison/PythonistaScripts#18]
I'm getting name not defined error on line 72:

files_found = does_directory_contain_files(config, full_path)

I'm not sure how to get it to work. I'm new to pythonista.

**Comment by dhutchison** [comment]
@revkamcclain using latest version? Running script from root directory or somewhere else?

**Comment by revkamcclain** [comment]
I am running from the root directory. And all my scripts are in the root, for the most part. Where should I run it from?

**Comment by dhutchison** [comment]
@revkamcclain I'm just trying to establish what's different. Works for me in the same state.

**Comment by revkamcclain** [comment]
Thanks for helping! I ran it again and it seemed to hang up in the process_folder function. I attached a screenshot of the error message. It seems, as best as I can understand it, to check all my local files, but then sits for a few minutes after checking the last one, and then kicking to this error. 

![image](https://cloud.githubusercontent.com/assets/16677792/12896956/ba9f12b6-ce72-11e5-9405-80f43c46eb7d.png)

**Comment by dhutchison** [comment]
Hmmm. Are you able to provide a directory listing? What folders are there?

**Comment by revkamcclain** [comment]
Here you go:
![image](https://cloud.githubusercontent.com/assets/16677792/12917602/3d5506c6-cf08-11e5-98f8-edf6e92cedbd.png)

**Comment by apsteinmetz** [comment]
I have the same problem.  Dropboxsync.py is in root. I don't know where does_directory_contain_files would be. What module is it from?  FWIW the "full_path" that is passed to the function is the examples/animation directory.  I don't know why that would be.

![image](https://cloud.githubusercontent.com/assets/10889837/12933500/4d3e3226-cf56-11e5-8e21-b6de80457937.png)

**Comment by dhutchison** [comment]
I've spotted the issue - replace does_directory_contain_files with can_sync_local_directory 

I've got some other changes to test before I can push a commit.

**Comment by dhutchison** [comment]
Method should be

```
def can_sync_local_directory(config, local_folder):

    if os.path.exists(local_folder) and not os.path.relpath(local_folder, PYTHONISTA_DOC_DIR) in config['skip_files'] and not os.path.dirname(local_folder).startswith('.'):
        files = os.listdir(local_folder)
        for current_file in files:

            full_path = os.path.join(local_folder, current_file)
            relative_path = os.path.relpath(full_path, PYTHONISTA_DOC_DIR)
            db_path = '/'+relative_path

            if can_sync_local_file(config, full_path):
                return True

            elif os.path.isdir(full_path):

                    files_found = can_sync_local_directory(config, full_path)

                    if files_found:
                        # Something in the directory needs to be synced
                        return True


    logging.debug('Directory %s does not contain any files for sync', local_folder)
    return False

```

**Comment by dhutchison** [comment]
Should be fixed now, could someone independently confirm? 

Thanks.
