### ISSUE TITLE
subfolders.

### ISSUE THREAD

**Issue by Tkizzy** [dhutchison/PythonistaScripts#19]
Hi I'm not sure if I have this exact version of the script. The version I have has some problems with syncing subfolders for example if there is externally ...

FolderA/ (files) + (FolderB)/files

when it downloads in pythonista it creates two folders with the one with the subdirectory being lowercase

foldera/folderb/files

and

FolderA/files

Does this version of the script exhibit this behavior?

**Comment by dhutchison** [comment]
@Tkizzy are you able to provide a directory listing of the Dropbox side just so I'm clear what the structure is?

I'll take a look at it later, it's not an issue I've seen before.

**Comment by dhutchison** [comment]
Closing as no response - can't reproduce
