### ISSUE TITLE
Nested folders are not supported

### ISSUE THREAD

**Issue by cclauss** [dhutchison/PythonistaScripts#2]
As mentioned in both https://forum.omz-software.com/topic/2140/a-tale-of-two-dropboxsyncs and https://forum.omz-software.com/topic/2560/sync-between-devices-how-to/9

**Comment by dhutchison** [comment]
@cclauss it has been on my todo list for a while - I'll try at least having a look at it tonight. I've not touched python in months but!

**Comment by dhutchison** [comment]
Figured out the issue with uploading. It's going to require a bit more testing - hopefully get a new version up Sunday.

**Comment by dhutchison** [comment]
Latest commit should resolve the issue (and add pyui file support).
