### ISSUE TITLE
Dangerous instruction could lead to accidental deletion

### ISSUE THREAD

**Issue by karlic** [dhutchison/PythonistaScripts#22]
Lines 211 and 212 have the same instruction for download and deletion.

```
Delete From Dropbox (d) [All in this state (da)]
Download File (l) [All in this state (da)]
```

Typing da would result in deletion NOT download.

The issue arises because [D]elete and [D]ownload start with the same letter. Why not use
1. [R]emove From Dropbox and [D]ownload File or
2. [D]elete From Dropbox and [G]et File

I prefer 1.

**Comment by dhutchison** [comment]
Just looks to be a mistake in the prompt, "la" will download all (following the pattern of all the other prompts). 

Feel free to submit a pull request to change it, I won't be in front of a device to commit a change till the weekend.

**Comment by karlic** [comment]
I think that's it done. Replaced 'da' with 'la' in the prompt. I think this is part of a bigger issue though, so will raise another issue.
