### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by iccentt** [dhutchison/PythonistaScripts#25]
I ran smoothly up until yesterday, and then today "No JSON object could be decoded" error appear. 
I tried to upload your original file again but same message appear.

**Comment by dhutchison** [comment]
I suspect there is some special character in one of the file paths which is not correctly encoded to be valid JSON. 

Is it possible for you to send me your "dropbox_sync/file.cache.txt" file so I can take a look? You can email it to David at devwithimagination dot com.

**Comment by dhutchison** [comment]
Closing as not reproducible.
