### ISSUE TITLE
DropboxSync.py invalid path error if it is not in the root folder

### ISSUE THREAD

**Issue by BalurPoco** [dhutchison/PythonistaScripts#4]
If I put the script for example under /Tools/Sync folder, it will give me an error.
ErrorResponse: [400] {u'path':u'Invalid path \'/../../Backups\': bad path component 1: ".."'}
Line 94: process_folder

No error when it's in /.

**Comment by dhutchison** [comment]
Fixed, see latest commit. 

Turns out I'd introduced some relative path assumptions.
