### ISSUE TITLE
Feature request: Exluding folder paths

### ISSUE THREAD

**Issue by BalurPoco** [dhutchison/PythonistaScripts#6]
In my case I have an /Examples forder in my root and I do not want to be checked all the time because it's not changing.

**Comment by ruudvanderham** [comment]
I support the request. In my case it's about the sympy package, which dorsn't need to be synched at all.

**Comment by dhutchison** [comment]
I see the need for a config file coming...

@upwart - is there ever a need for that folder to be synced or is it an install location for a library or something?

**Comment by ruudvanderham** [comment]
In which you could place the appkey, appsecret an the token (?).
Maybe you coukd also make the program a bit less verbose. Now the program writes quite often lists, tuples (mostly empty)', 404 codes, hashes which must have been very useful in the testing phase, but should be suppressed. Even trying to upload is not required in the 'production version'.

**Comment by BalurPoco** [comment]
I support @upwart 's request.

**Comment by dhutchison** [comment]
I'm working on log verbosity just now (since it is handy for Dev there will be a few log levels - moving to the python Logging framework). 

Bug will be handled after this.

**Comment by dhutchison** [comment]
Latest commit brings some pretty big changes:
- script no longer should require to be tweaked for each user. First run will prompt for the app secret & key, then store that in a configuration file which is synced. 
- run with the "-c" argument will prompt for additional file extensions to include, as well as any files / folders to skip. This configuration file is held in the dropbox_sync folder. The old token file is no longer required.
