### ISSUE TITLE
Locally deleted folders, dropbox empty folder

### ISSUE THREAD

**Issue by BalurPoco** [dhutchison/PythonistaScripts#7]
If i delete a folder locally and sync, files will be deleted on dropbox too, but still have that folder empty.

**Comment by dhutchison** [comment]
Fixed in latest commit.

**Comment by BalurPoco** [comment]
Sorry, my previous comment was a mess, I had to re-write it.

Empty folder deleting is not working properly.
If I have a folder named Backups with just zip files in it, it's also want to delete that folder. I think you need to check all files not just file_extensions elements.

**Comment by dhutchison** [comment]
@Balur86 can you run the script with "-vv" argument and share the log statement starting "Pre-delete metadata"?

Before it attempts to delete a Dropbox directory it checks it has no contents (at all, not just looking at file extensions).

**Comment by dhutchison** [comment]
@Balur86 Ignore last comment, I got your previous comment in an email notification and it actually makes more sense. 

The remote directory is empty but your local version of it isn't? I think it should be deleting the remote one, but it also shouldn't be creating the remote directory if it contains no eligible files. 

I'll take a look at the latter issue in the next few days and try to tidy it up now I've got an example.

**Comment by BalurPoco** [comment]
@dhutchison Here is the result:

```
Processing local dir /Backups from /
metadata: {u'size': u'0 bytes', u'is_deleted': True, u'rev': u'415437bf697', u'thumb_exists': False, u'bytes': 0, u'modified': u'Sat, 30 Jan 2016 08:46:00 +0000', u'contents': [], u'path': u'/Backups', u'is_dir': True, u'icon': u'folder_gray', u'root': u'app_folder', u'hash': u'83f80c2a84a13d61b061c36287392b5e', u'revision': 1045}
Skipping extension .zip
Skipping extension .zip
Skipping extension .zip
Skipping extension .zip
Remote directory /Backups is empty, deleting...
Pre-delete metadata {u'hash': u'c223b988e34a4b367f3cf3098661e87a', u'revision': 1046, u'bytes': 0, u'thumb_exists': False, u'rev': u'416437bf697', u'modified': u'Sat, 30 Jan 2016 08:47:24 +0000', u'path': u'/Backups', u'is_dir': True, u'icon': u'folder', u'root': u'app_folder', u'contents': [], u'size': u'0 bytes'}
Writing sync state to /private/var/mobile/Containers/Shared/AppGroup/9DFC6D70-B016-431E-B677-C832FCDB1A61/Documents/Tools/Sync/file.cache.txt
Dropbox sync done!
```

So local Backups folder only contains .zip files, and Backups folder is not exists on Dropbox.

**Comment by BalurPoco** [comment]
Sorry if I was not obvious.

Local side:
- Backups/abc.zip
- Backups/def.zip
- Backups/xyz.zip

Dropbox side:
- No Backups folder.

Console output:

```
Begin Dropbox sync
Linked account: my name
Remote directory /Backups is empty, deleting...
Dropbox sync done!
```

**Comment by dhutchison** [comment]
@Balur86 can you let me know if the latest commit resolves the issue?

It should skip over any directories now which don't contain any eligible files.

**Comment by BalurPoco** [comment]
@dhutchison Yes. It works perfectly.
